import React, { useEffect, useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, ClipboardCheck, Plus, Search } from "lucide-react";
import api from "./api";
const page = { maxWidth: 1200, margin: "0 auto", padding: "8px 0 40px" };
const card = { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 18, padding: 18, boxShadow: "0 8px 24px rgba(15,23,42,.05)" };
const btn = { border: "0", borderRadius: 10, padding: "10px 14px", cursor: "pointer", fontWeight: 700 };
const input = { width: "100%", boxSizing: "border-box", padding: "11px 12px", border: "1px solid #d1d5db", borderRadius: 10, outline: "none" };
const label = { display:"block", fontSize:12, fontWeight:800, marginBottom:6, color:"#475569" };
function fmt(v) { return v ? new Date(v).toLocaleDateString() : "—"; }
function cls(v) { return String(v || "").toLowerCase().replaceAll(" ", "-"); }

export default function FollowUp(){
 const [items,setItems]=useState([]),[cases,setCases]=useState([]),[animals,setAnimals]=useState([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({case_id:"",animal_id:"",animal_name:"",scheduled_date:new Date(Date.now()+7*864e5).toISOString().slice(0,10),purpose:"Post-treatment follow-up",assigned_to:"",notes:"",status:"Scheduled"});
 async function load(){setLoading(true);setError("");try{const [f,c,a]=await Promise.all([api.followUps.list(),api.cases.list(),api.animals.list()]);setItems(f.items||[]);setCases(c.items||[]);setAnimals(a.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>[x.animal_name,x.purpose,x.status,x.assigned_to].join(" ").toLowerCase().includes(q.toLowerCase())),[items,q]);
 function chooseCase(id){const c=cases.find(x=>x.id===id);const a=animals.find(x=>x.id===c?.animal_id);setForm(f=>({...f,case_id:id,animal_id:c?.animal_id||"",animal_name:c?.animal_name||a?.name||""}))}
 async function save(){if(!form.animal_name||!form.scheduled_date){setError("Animal and scheduled date are required.");return}setSaving(true);try{await api.followUps.create(form);setOpen(false);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function complete(id){try{await api.followUps.update(id,{status:"Completed"});await load()}catch(e){setError(e.message)}}
 return <div style={page}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap",marginBottom:18}}><div><h1 style={{margin:0}}>Follow-up Care</h1><p style={{color:"#64748b",margin:"6px 0 0"}}>Track post-treatment reviews and case closure.</p></div><button style={{...btn,background:"#7c3aed",color:"#fff",display:"flex",gap:7}} onClick={()=>setOpen(true)}><Plus size={16}/> Schedule Follow-up</button></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginBottom:18}}>{[["Total",items.length],["Scheduled",items.filter(x=>x.status!=="Completed").length],["Completed",items.filter(x=>x.status==="Completed").length],["Cases linked",items.filter(x=>x.case_id).length]].map(([t,v])=><div key={t} style={card}><div style={{color:"#64748b",fontWeight:700}}>{t}</div><div style={{fontSize:30,fontWeight:900,marginTop:9}}>{v}</div></div>)}</div>
 <div style={{...card,marginBottom:14}}><div style={{display:"flex",gap:8,alignItems:"center",border:"1px solid #e5e7eb",borderRadius:10,padding:10}}><Search size={17}/><input style={{border:0,outline:0,width:"100%"}} placeholder="Search animal, purpose or assignee" value={q} onChange={e=>setQ(e.target.value)}/></div></div>
 {error&&<div style={{...card,marginBottom:14,borderColor:"#fecaca",color:"#b91c1c"}}>{error}</div>}
 <div style={card}>{loading?<p>Loading follow-ups...</p>:filtered.length===0?<p style={{color:"#64748b"}}>No follow-ups scheduled.</p>:<div style={{display:"grid",gap:10}}>{filtered.map(x=><div key={x.id} style={{display:"grid",gridTemplateColumns:"1.3fr 1fr 1fr 1fr auto",gap:10,alignItems:"center",border:"1px solid #e5e7eb",borderRadius:14,padding:13}}><div><b>{x.animal_name}</b><div style={{fontSize:12,color:"#64748b"}}>{x.purpose}</div></div><div><span style={{display:"inline-flex",alignItems:"center",gap:6}}><CalendarClock size={15}/>{fmt(x.scheduled_date)}</span></div><div><div style={{fontSize:12,color:"#64748b"}}>Assigned to</div><b>{x.assigned_to||"Unassigned"}</b></div><div><span style={{padding:"5px 9px",borderRadius:999,background:x.status==="Completed"?"#dcfce7":"#ede9fe",fontSize:12,fontWeight:800}}>{x.status}</span></div><div>{x.status!=="Completed"?<button style={{...btn,background:"#111827",color:"#fff"}} onClick={()=>complete(x.id)}>Complete</button>:<CheckCircle2/>}</div></div>)}</div>}</div>
 {open&&<div style={{position:"fixed",inset:0,background:"rgba(15,23,42,.45)",display:"grid",placeItems:"center",zIndex:50,padding:16}}><div style={{...card,width:"min(640px,100%)"}}><div style={{display:"flex",justifyContent:"space-between"}}><h2 style={{margin:0}}>Schedule Follow-up</h2><button style={btn} onClick={()=>setOpen(false)}>✕</button></div><div style={{display:"grid",gap:12,marginTop:14}}><div><label style={label}>Related Case</label><select style={input} value={form.case_id} onChange={e=>chooseCase(e.target.value)}><option value="">Select case</option>{cases.map(c=><option key={c.id} value={c.id}>{c.animal_name} — {c.condition}</option>)}</select></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div><label style={label}>Animal</label><input style={input} value={form.animal_name} onChange={e=>setForm({...form,animal_name:e.target.value})}/></div><div><label style={label}>Date</label><input type="date" style={input} value={form.scheduled_date} onChange={e=>setForm({...form,scheduled_date:e.target.value})}/></div></div><div><label style={label}>Purpose</label><input style={input} value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></div><div><label style={label}>Assigned To</label><input style={input} placeholder="Veterinarian / Field Worker" value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}/></div><div><label style={label}>Notes</label><textarea style={{...input,minHeight:90}} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></div><button disabled={saving} style={{...btn,width:"100%",marginTop:16,background:"#7c3aed",color:"#fff"}} onClick={save}>{saving?"Saving...":"Schedule Follow-up"}</button></div></div>}
 </div>
}
